// Kerry page data — TA-v3 exports for all 38 certified symbol/TF pairs.
//
// Generated by scripts/gen_kerry_ta_v3.py (dual hash-gate: output_csv_sha256
// verified, ts_aligned + input_row_match asserted). JSON conforms to the
// TaV3Export contract so SandboxChart renders it without modification.

import { useTaV3Export, type ExportState } from './taV3Export'

export const KERRY_SYMBOLS = [
  'BTCUSDT', 'ETHUSDT', 'BNBUSDT', 'SOLUSDT', 'XRPUSDT',
  'DOGEUSDT', 'SUIUSDT', 'FETUSDT', 'PEPEUSDT', 'SHIBUSDT',
] as const
export type KerrySym = (typeof KERRY_SYMBOLS)[number]

export const KERRY_TIMEFRAMES = ['5m', '1h', '4h', '1D'] as const
export type KerryTf = (typeof KERRY_TIMEFRAMES)[number]

// DOGE only has 5m and 1h
const DOGE_TFS: KerryTf[] = ['5m', '1h']
export function availableTfs(sym: KerrySym): KerryTf[] {
  return sym === 'DOGEUSDT' ? DOGE_TFS : [...KERRY_TIMEFRAMES]
}

export function kerryPath(sym: KerrySym, tf: KerryTf): string {
  return `${import.meta.env.BASE_URL}data/kerry_ta_v3_${sym}_${tf}.json`
}

export const KERRY_PROVENANCE_PATH = `${import.meta.env.BASE_URL}data/kerry_ta_v3_provenance.json`

export function useKerryExport(sym: KerrySym, tf: KerryTf): ExportState {
  return useTaV3Export(kerryPath(sym, tf))
}

export interface KerryProvenancePair {
  csvSha256: string
  manifestSha256: string
  rows: number
  canonicalRows: number
  columnCount: number
  windowStart: string
  windowEnd: string
  gateVerdict: string
  fileSizeKb: number
  real: boolean
}

export interface KerryProvenance {
  manifestType: string
  taVersion: string
  evidenceDir: string
  generatedAt: string
  windowMode: string
  windowN: Record<string, number>
  pairs: Record<string, Record<string, KerryProvenancePair>>
  symbolTimeframes: Record<string, string[]>
  windowing: { mode: string; n: Record<string, number>; note: string }
}
